name = "MyExample"
uuid = "12ff83ca-6270-4f3c-964c-a154679f2062"
authors = ["Torres Trovik"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
